config/routes.rb
Rails.application.routes.draw do
  root to: "metrics#index"
  resources :metrics, only: [:index, :show] do
    resources :metrics_values, only: [:edit, :update]
  end
end

app/models/metric.rb
class Metric
  @@client = HooplaClient.hoopla_client
  attr_reader :metric_response

  def self.all
    metric_response = @@client.get("/metrics", {"Accept" => "application/vnd.hoopla.metric-list+json"})
    metric_response.map {|response| Metric.new(response) }
  end

  def self.find(id)
    metric_response = @@client.get("/metrics/#{id}", {"Accept" => "application/vnd.hoopla.metric+json"})
    Metric.new(metric_response)
  end

  def initialize(metric_response)
    @metric_response = metric_response
  end

  def name
    @name ||= metric_response["name"]
  end

  def id
    @id ||= metric_response["href"].split("/").last
  end

  def list_metric_values
    MetricValues.all(id)
  end
end

app/models/metric_values.rb
class MetricValues
  @@client = HooplaClient.hoopla_client
  attr_reader :metric_value_response

  def self.all(metric_id)
    response = @@client.get("/metrics/#{metric_id}/values", {"Accept" => "application/vnd.hoopla.metric-value-list+json"})
    metric_values = response.map {|resp| MetricValues.new(resp) }.select(&:is_user?) # easier to query by user to the api// TODO: figure that out
    metric_values
  end

  def self.find(metric_id, id)
    MetricValues.new(@@client.get("/metrics/#{metric_id}/values/#{id}", {"Accept" => "application/vnd.hoopla.metric-value+json"}))
  end

  def self.update(metric_id, id, params)
    path = "/metrics/#{metric_id}/values/#{id}"
    headers = {"Content-Type" => "application/vnd.hoopla.metric-value+json"}
    @@client.put(path, params, headers)
  end

  def initialize(metric_value_response)
    @metric_value_response = metric_value_response
  end

  def id 
    metric_value_response["href"].split("/").last
  end

  def href
    metric_value_response["href"]
  end

  def value 
    metric_value_response["value"]
  end

  def owner
    metric_value_response["owner"]
  end

  def metric
    metric_value_response["metric"]
  end

  def owner_href
    owner["href"]
  end

  def updated_at
    metric_value_response["updated_at"]
  end

  def is_user?
    owner["kind"] == "user"
  end
end

app/models/user.rb
class User
  @@client = HooplaClient.hoopla_client
  attr_reader :response

  def self.get_all
    response = @@client.get("https://api.hoopla.net/users", {"Accept" => "application/vnd.hoopla.user-list+json"})
    response.map {|resp| User.new(resp) }
  end

  def initialize(response)
    @response = response
  end

  def id
    href.split("/").last
  end

  def href
    response["href"]
  end

  def email
    response["email"]
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def first_name
    response["first_name"]
  end
  def last_name 
    response["last_name"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :get_client

  def get_client
    @hoopla_client = HooplaClient.hoopla_client
#    @descriptor = HooplaClient.client.get('/', {'Accept' => 'application/vnd.hoopla.api-descriptor+json'})
  end
end

app/controllers/metrics_controller.rb
class MetricsController < ApplicationController
  
  def index
    @metrics = Metric.all
  end

  def show
    @metric = Metric.find(params[:id])
    @users = User.get_all
    @metric_values = @metric.list_metric_values
  end
end

app/controllers/metrics_values_controller.rb
class MetricsValuesController < ApplicationController

  def edit
    @metric_value = MetricValues.find(params[:metric_id], params[:id])
  end

  def update
    begin
      MetricValues.update(params[:metric_id], params[:id], permited_params)
      redirect_to metric_path(params[:metric_id])
    rescue StandardError => e
      @metric_value = MetricValues.find(params[:metric_id], params[:id])
      @error = e.message
      render :edit
    end
  end

  def permited_params
    params.permit(:value, :owner, :href, :metric, :updated_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def select_user_name(metric, users)
    users.find {|user| user.href == metric.owner_href }.full_name
  end
end

app/helpers/hoopla_client.rb
require 'faraday'
require 'faraday_middleware'

class HooplaClient
  CLIENT_ID = ENV['CLIENT_ID']
  CLIENT_SECRET = ENV['CLIENT_SECRET']
  PUBLIC_API_ENDPOINT = 'https://api.hoopla.net'

  def initialize
    descriptor
  end

  def self.hoopla_client
    @@hoopla_client_singleton ||= HooplaClient.new
  end

  def get(relative_url, options)
    response = client.get(relative_url, headers: options)
    if response.status == 200
      JSON.parse(response.body)
    else
      raise StandardError, 'Invalid response from '
    end
  end

  def put(relative_url, params, options)
    response = client.put(relative_url, params.to_json, options)
    if response.status == 200
      JSON.parse(response.body)
    else
      raise StandardError, "Invalid response from #{response.body}"
    end
  end

  def get_relative_url(link)
    descriptor['links'].find { |l| l['rel'] == link }['href'].delete_prefix descriptor['href']
  end

  private

  def connection
    @conn ||= Faraday.new(url: PUBLIC_API_ENDPOINT) do |faraday|
      faraday.response :logger
      faraday.adapter Faraday.default_adapter
      faraday.basic_auth CLIENT_ID, CLIENT_SECRET
    end
  end

  def login
    response = connection.post('oauth2/token') do |req|
      if @refresh_token
        req.params['grant_type'] = 'refresh_token'
        req.params['refresh_token'] = @refresh_token
      else
        req.params['grant_type'] = 'client_credential'
      end
    end

    if response.status == 200
      json_resp = JSON.parse(response.body)
      @token = json_resp['access_token']
      @refresh_token = json_resp['refresh_token']
    else
      if (@token.nil? && @refresh_token.nil?)    # Nothing to retry
        raise ActiveResource::UnauthorizedAccess
      else
        @token = nil
        @refresh_token = nil
      end
    end
    @token
  end

  def token
    if !@token
      login

      if !@token # login failed
        login
      end

      # Either it's succeeded or raised an execption
    end
    @token
  end

  def client
    @client ||= Faraday.new(url: PUBLIC_API_ENDPOINT) do |faraday|
      faraday.response :logger
      faraday.adapter Faraday.default_adapter
      faraday.use FaradayMiddleware::EncodeJson
      faraday.authorization :Bearer, token
    end
  end

  def parse_response(verb, url, response)
    if [200, 201].include? response.status
      JSON.parse(response.body)
    else
      raise StandardError, 'Invalid response from #{verb} #{url}: #{response.status}: #{response.body'
    end
  end

  def descriptor
    descriptor_url = PUBLIC_API_ENDPOINT
    @descriptor ||= self.get(descriptor_url, {'Accept' => 'application/vnd.hoopla.api-descriptor+json'})
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HooplaRailsMetricsQuiz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/metrics/index.html.erb
<h1>Metrics</h1>

<ul>
  <% @metrics.each do |metric| %>
    <li><%= link_to metric.name, metric_path(metric.id) %></li>
  <% end %>
</ul>

app/views/metrics/show.html.erb
<h1>Metric: <%= @metric.name %></h1>
<table>
  <thead>
    <tr>
      <td>id</td>
      <td>Value</td>
      <td>Owner</td>
      <td></td>
    </tr>
  </thead>
  <tbody>
    <% @metric_values.each do |metric_value| %>
      <tr>
        <td><%= metric_value.id %></td>
        <td><%= link_to metric_value.value, edit_metric_metrics_value_path(@metric.id, metric_value.id) %></td>
        <td><%= select_user_name(metric_value, @users) %></td>
        <td><%= link_to "edit", edit_metric_metrics_value_path(@metric.id, metric_value.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/metrics_values/edit.html.erb
<%= form_tag(metric_metrics_value_path(params[:metric_id], params[:id]), method: :put) do |f| %>
  <div>
    <%= text_field_tag :value, @metric_value.value %> 
    <%= hidden_field_tag :owner, @metric_value.owner %>
    <%= hidden_field_tag :href, @metric_value.href %>
    <%= hidden_field_tag :metric, @metric_value.metric %>
    <%= hidden_field_tag :updated_at, @metric_value.updated_at %>
  </div>
  <div>
    <%= submit_tag 'Save' %>
  </div>
<% end %>

<%= @error %>